version = 3.11.5
runner.dialect = Scala212Source3
docstrings.style = keep
style = defaultWithAlign
assumeStandardLibraryStripMargin = true
project.git = true
project.excludeFilters = [
  # TODO https://github.com/portable-scala/sbt-crossproject/pull/173
  "sbt-crossproject/src/main/scala-3/sbtcrossproject/CrossPluginCompat.scala"
]
