style = defaultWithAlign
docstrings = JavaDoc
assumeStandardLibraryStripMargin = true
project.git = true
project.excludeFilters = [
  # TODO https://github.com/portable-scala/sbt-crossproject/pull/173
  "sbt-crossproject/src/main/scala-3/sbtcrossproject/CrossPluginCompat.scala"
]
