name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v5
      - name: Install Scala Native dependencies
        run: sudo apt-get install libgc-dev libunwind8-dev
      - name: scalafmt
        run: ./scripts/scalafmt --test
      - name: MiMa
        run: sbt ";sbt-crossproject/mimaReportBinaryIssues;sbt-scalajs-crossproject/mimaReportBinaryIssues;sbt-scala-native-crossproject/mimaReportBinaryIssues"
      - name: Test
        run: sbt sbt-crossproject-test/scripted
